{% set name = "memory-allocator" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/memory_allocator-{{ version }}.tar.gz
  sha256: 675d3c91019db98c97441de73d5c648821e5ae813f3f54cd09863d474b48fe26

build:
  number: 0
  skip: true  # [py<312]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - cross-python_{{ target_platform }}   # [build_platform != target_platform]
    - python                               # [build_platform != target_platform]
    - cython >=3.0                         # [build_platform != target_platform]
    - meson-python >=0.15.0               # [build_platform != target_platform]
    - meson >=1.2.0                        # [build_platform != target_platform]
    - ninja                                # [build_platform != target_platform]
  host:
    - python
    - pip
    - cython >=3.0
    - meson-python >=0.15.0
    - meson >=1.2.0
    - ninja
  run:
    # this is an extension to cython, so cython is needed at runtime
    - cython >=3.0
    - python

test:
  imports:
    - memory_allocator
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/sagemath/memory_allocator
  summary: An extension class to allocate memory easily with cython
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - isuruf
