{% set name = "memory-allocator" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/memory_allocator-{{ version }}.tar.gz
  sha256: ddf42a2dcc678062f30c63c868335204d46a4ecdf4db0dc43ed4529f1d0ffab9

build:
  number: 3
  skip: true  # [py2k]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - cython                               # [build_platform != target_platform]
    - cross-python_{{ target_platform }}   # [build_platform != target_platform]
    - python                               # [build_platform != target_platform]
    - pip                                  # [build_platform != target_platform]
  host:
    - cython
    - pip
    - python
  run:
    # this is an extension to cython, so cython is needed at runtime
    - cython
    - python

test:
  imports:
    - memory_allocator
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/kliem/memory_allocator
  summary: An extension class to allocate memory easily with cython
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - isuruf
